src/features/index/index.tsx, src/pages/_document.tsx, src/styles/global.scss, tailwind.config.js
- close #29 
- Figma準拠のカラーパレットを追加
- Figmaで使用したグラデーションを易しく利用できるユーティリティクラス `.gradient-primary` `.gradient-game-xeno` `.gradient-*` の作成
- Figmaで使用したフォント群を`.font-body` `.font-branding` `.font-pixel`から利用可能に
=> .tailwind.config.jsにFigma準拠のカラーパレット、グラデーションとフォントの設定を追加する

src/components/Card/Card.story.tsx, src/components/Card/index.tsx
- close #26 
コンテンツを内包するのに繰り返し使い回されるであろう`Card`を作成した。
説明に書いてある`className`の使い方の制約はほぼ気にしなくていい..
=> `<Card>`コンポーネントの作成

package.json, src/components/Button/Button.story.tsx, src/components/Button/index.tsx, src/components/Navigation/Navigation.story.tsx, src/components/Navigation/index.tsx, yarn.lock
- close #5 
- close #48 
マウスでホバーして一時表示、もしくはクリックでトグル表示できる吹き出しメニューが付随するナヴィゲーションメニューを作成できるコンポーネント群`<NavigationMenu>`を作成した。
吹き出しの表示位置の右寄せ、中央寄せ、左寄せ等の調整は`viewportClassName`属性から吹き出しメニュー`<NavigationContent>`の親要素にスタイルを当てることで実現可能。
```tsx
<NavigationMenu className="justify-center bg-white">
<NavigationItem>
<NavigationTrigger>
<div className="flex px-4 py-2 font-bold">
<NavigationLink>
<a href="https://example.com/">Games</a>
</NavigationLink>
</div>
</NavigationTrigger>
<NavigationContent className="bg-gradient-to-br font-bold text-white gradient-game">
Xeno, Ice Raze, 大富豪などの6種のゲームで遊びましょう！
</NavigationContent>
</NavigationItem>
<NavigationItem>
<NavigationTrigger>
<div className="flex px-4 py-2 font-bold">
<NavigationLink>
<a href="https://example.com/">Ranking</a>
</NavigationLink>
</div> …
```
=> `<NavigationMenu>`と関連コンポーネント群`<NavigationItem>` `<NavigationTrigger>` `<NavigationContent>` `<NavigationLink>`の作成

src/components/Modal/Modal.story.tsx, src/components/Modal/index.tsx
- close #44 
- close #53 
#44と#53でブランチとPRを分けてやると、あとあとコンフリクトの解消が面倒そうだったのでまとめました。
HamburgerMenu #2 で`<Modal>`を再利用するために必須だったので、オーバレイとコンテンツのスタイルを露出させました。それに伴い`<Modal>`に与える子要素の構造も変更が加わっています。
**現在、`shadow-z16`等のシャドークラスの上書きができない #54 ので、はやめに直します。**
```tsx
<Modal
trigger={
<Button onClick={action('onClick [モーダルを開くボタンが押されました。]')} {...args}>
モーダルを開く
</Button>
}
>
<ModalOverlay className="bg-gradient-to-br gradient-primary"> {/* ←これを追加 */}
<ModalContent className="bg-transparent text-white shadow-none"> {/* ←これを追加 */}
<ModalTitle>本当に良いのですか？</ModalTitle>
<ModalDescription>この動作をすると何かが起こります。画面外をクリックすると閉じることができます。</ModalDescription>
<Button onClick={action('onClick [モーダルの中の確定ボタンが押されました。]')}>
確定<span className="text-neutral-700">押しても閉じないよ</span>
</Button>
</ModalContent>
</ModalOverlay>
</Modal>
``` …
=> モーダルの`<ModalOverlay>``<ModalContent>`の露出とボタングループ用の`<ModalButtonGroup>`の追加

src/libs/twmerge/index.ts, src/libs/twmerge/twmerge.spec.ts
=> TailwindCSSの独自クラスの`shadow-z*` `rounded-base` `gradient-*` の対立が解決できない問題を解決した。

package.json, src/components/Label/index.tsx, src/components/Radio/Radio.story.tsx, src/components/Radio/RadioItem.story.tsx, src/components/Radio/index.tsx, yarn.lock
- close #57
キーボード操作などのアクセシビリティとスタイルの自由度が確保されたラジオボタンのためのコンポーネント群です。
```tsx
<form>
<RadioGroup
defaultValue="apple"
loop
name="fruit"
onValueChange={() => {}}
required
>
<div className="flex flex-row justify-start gap-2">
<RadioItem
id="radio-option-1"
value="apple"
>
<RadioIndicator />
</RadioItem>
<Label htmlFor="radio-option-1">
林檎
</Label>
</div>
<div className="flex flex-row justify-start gap-2">
<RadioItem
id="radio-option-2"
value="grape"
>
<RadioIndicator />
</RadioItem>
<Label htmlFor="radio-option-2">
葡萄
</Label>
</div>
<div className="flex flex-row justify-start gap-2">
<RadioItem
disabled
id="radio-option-3"
value="iyokan"
>
<RadioIndicator />
</RadioItem>
<Label htmlFor="radio-option-3">
伊予柑
</Label>
</div>
</RadioGroup>
</form>
```
=> ラジオボタン用のコンポーネント`<RadioGroup>` `<RadioItem>` `<RadioIndicator>`を作成した。

package.json, src/components/Selector/Selector.story.tsx, src/components/Selector/SelectorItem.story.tsx, src/components/Selector/index.tsx, yarn.lock
- close #49 
`@radix-ui/react-select`を使用することで、キーボード操作が可能でアクセシビリティの確保されたセレクタを作成した。
セレクタの選択肢内のグルーピングと区分けによる整理が可能。
選択肢の表示に、テキストのみならずアイコン等を使用可能。
```tsx
<Selector
aria-label="category"
>
<SelectorGroup label="日付ごと">
<SelectorItem value="day1">
一日目のみ
</SelectorItem>
<SelectorItem value="day2">
二日目のみ
</SelectorItem>
</SelectorGroup>
<SelectorSeparator />
<SelectorGroup label="使用キャラごと">
<SelectorItem value="fox">
<Icon
alt="きゅうびさんの画像"
className="h-6"
src="/icons/fox.png"
/>
<span className="font-bold">
きゅうびさん
</span>
のみ
</SelectorItem>
<SelectorItem value="cat">
<Icon
alt="ねこさんの画像"
className="h-6"
src="/icons/cat.png"
/>
<span className="font-bold">
ねこさん
</span>
のみ
</SelectorItem>
</SelectorGroup>
</Selector>
```
=> `<Selector>`を始めとするセレクターを提供するコンポーネント群を追加した。

src/components/Link/Link.story.tsx, src/components/Link/index.tsx
- close #59 
ただの`next/link`のラッパーです。ですが、与えられる子要素は`<LinkIcon>`とテキストのみに制限しています。
```tsx
<Link href='/user' className='text-lg text-info-700'>
<LinkIcon>
<HiUserCircle />
</LinkIcon>
あなたのプロフィール
</Link>
```
このように`react-icon`のコンポーネントを与えるだけで、自動的にアイコンの大きさの調整と色の適用をしてくれます。
=> アイコンを付随させて使いやすい、スタイル付きのnext/linkのラッパーである<Link>を作成した。

src/components/Radio/Radio.story.tsx, src/components/Radio/RadioItem.story.tsx
- close #61 
ストーリー`With Custom Style`での選択肢`<RadioItem>`のスタイルの高さ指定を`h-fit`から`h-auto`へ変更した。これにより意図した通りに大きな選択肢が表示される。
=> `<RadioGroup>` `<RadioItem>`のストーリーで使われていた例のスタイルを、意図していたものに修正した。

src/libs/graphql/documents/query/FindUsers.gql, src/libs/graphql/generated/graphql.ts, src/libs/graphql/schema.json
- close #64 
```tsx
export enum Character {
Cat = 'CAT',
Fox = 'FOX',
Goku = 'GOKU',
Pudding = 'PUDDING',
Reaper = 'REAPER',
Tree = 'TREE'
}
```
などの型を、コンポーネント作成の際に利用したかったので追加しました。
=> GraphQLのスキーマ由来の型を生成するために、適当な`.gql`ファイルを追加した。

.storybook/preview.js, src/components/Modal/index.tsx, src/layouts/components/HamburgerMenu/HamburgerMenu.story.tsx, src/layouts/components/HamburgerMenu/index.tsx
- close #2
- close #66
ハンバーガーメニューを開くボタンのスタイルは外部から変更可能です。
含まれるリンクのルーティング先は仮のもののため要変更です。
Esc/Tab/Arrow Keyで操作可能です。
=> `<HamburgerMenu>`を追加した。また、`<ModalOverlay>`がモーダルの吹き出しのほかに子要素を持てるように変更した。

.storybook/preview.js
- close #128 
これでStorybookでもGoogle Fontsのフォントが使用可能になります！
=> StorybookでGoogle Fontsを読み込む`.scss`ファイルのパス指定を正しいものに修正した。

src/components/UserItem/index.tsx, src/features/ranking/components/RankedUserItem/RankedUserItem.story.tsx, src/features/ranking/components/RankedUserItem/index.tsx, src/features/ranking/components/RankedUserItem/resolveDescription.spec.ts, src/features/ranking/components/RankedUserItem/resolveDescription.ts
- close #146 
- close #152 
順位とポイントとユーザー情報を受け取る`<UserItem>`のラッパーです。
特筆すべきことはないと思います...
=> 順位付きのユーザー情報を表示するコンポーネント`<RankedUserItem>`を作成した。

src/styles/storybook.scss
- close #153
これでStorybookでのフォント表示が、細長いださいフォントじゃなくなります。
=> Storybookで読み込まれる`.scss`ファイルに、Figma準拠のデフォルトのフォント指定を追加した。

codegen.yml, package.json, src/libs/graphql/generated/graphql.ts, src/libs/graphql/schema.json, src/libs/urql/index.ts, src/libs/urql/scalarsExchange.ts, yarn.lock
- close #155 
> `any`だと何でもできて怖いから変えたいです
[公式のShowcaseで紹介されている`urql-custom-scalars-exchange`](https://github.com/clentfort/urql-custom-scalars-exchange)を用いて、
GraphQLのカスタムスカラー`DateTime`として受け取る、ISO8601で日付時刻を表す`string`を、パースして`Date`に解決するURQLのExchangeを追加しました。
=> `graphql-codegen`が生成するGraphQLのスカラー`DateTime`に対応するTypescriptの型が`any`から`Date`になるように変更した。

src/components/Input/Input.story.tsx, src/components/Input/hooks/useInputValidityState.ts, src/components/Input/index.tsx, tailwind.config.js
- close #158 
`<Input>`はただのスタイル付きのHTML`<input>`ラッパーです。
ですが、テキストフィールド型のもののみ使用可能にするために、利用可能な`type`を制限しています
Storybookを参照してください！！！
=> テキストフィールド型の入力欄を提供する`<Input>`と、それに付随する情報を表すコンポーネント群`<InputItem>` `<InputLabel>` `<InputMessage>`を作成した。

src/layouts/components/HamburgerMenu/index.tsx, src/layouts/components/PageNavigationMenu/index.tsx, src/layouts/components/UserNavigationMenu/index.tsx
- close #180 
テスト用の`https://example.com`はリンクの宛先から消滅しました。
=> 各コンポーネント内の`<Link>`の宛先`href`を正しいサイト内のルーティングのものに修正した。

src/layouts/Layout.story.tsx, src/layouts/components/AudioControlMenu/AudioControlMenu.story.tsx, src/layouts/components/AudioControlMenu/container.tsx, src/layouts/components/AudioControlMenu/formatDuration.ts, src/layouts/components/AudioControlMenu/hooks/useAudioControlMenu.ts, src/layouts/components/AudioControlMenu/index.tsx, src/layouts/components/AudioProvider/AudioProvider.story.tsx, src/layouts/components/AudioProvider/AudioProviderContainer.story.tsx, src/layouts/components/AudioProvider/container.tsx, src/layouts/components/AudioProvider/index.tsx, src/layouts/components/Header/Header.story.tsx, src/pages/_app.tsx, src/state/audio/audioAutoPlay.tsx, src/state/audio/audioControl.tsx, src/state/audio/audioRefReadOnly.tsx, src/state/audio/audioResource.tsx, src/state/recoilKeys.ts
- close #184
- 自動再生失敗時に、RecoilのAtom`AudioControl`のメンバ`hasAutoPlaySuceeded`に対応した値を設定する
- 自動再生失敗時に、ユーザーのインタラクト`e.g. 画面のタッチ`などにあわせて再生開始をできるようにする
実際にVercelのDeployを開いてみて曲を再生できるか試してみてください。
自動再生は制約的に実現不可能なのですが、ユーザーのインタラクト`e.g. 画面のタッチ`などにあわせて再生開始をすることはできるので、がんばります。(この機能は未実装です)
現在のパスに合わせて、自動で対応した曲の情報を解決して、RecoilのAtom`AudioResource`を介してUIに反映できている様子
=> RecoilのAtom`AudioResource`の値に応じて再生する曲を切り替え、`<audio>`タグの`ref`の共有と自動再生の管理を担うコンポーネント`<AudioProvider>`を作成する。

src/presentation/style/stylesheet/global.scss
- close #224 
`w-screen (100vw)`がスクロールバーの占拠分を考慮しない問題への応急措置として変更した。
=> fix: 🚑️ (style/stylesheet/global.scss) ページ全体が横にはみ出した要素を描画しないように変更した。

src/presentation/layout/component/signup-progress-notification-modal/hook/use-signup-progress-notification-modal.hook.ts, src/presentation/layout/component/signup-progress-notification-modal/signup-progress-notification-modal.container.tsx, src/presentation/layout/component/signup-progress-notification-modal/signup-progress-notification-modal.presenter.tsx, src/presentation/layout/component/signup-progress-notification-modal/signup-progress-notification-modal.story.tsx, src/presentation/layout/layout.container.tsx, src/presentation/layout/layout.story.tsx, src/presentation/primitive/component/modal/modal.presenter.tsx, src/presentation/primitive/component/modal/modal.story.tsx, src/presentation/relevant/auth/auth.page.tsx, src/use-case/user/use-current-user-authentication-status.use-case.ts
- close #237 
- close #239 
Firebaseで認証済みかどうかの判定が正しく行われるように修正した。
```ts
// 修正前
const hasUserAuthenticated = useMemo(() => !!currentUser, [currentUser]); // ユーザーがFirebase Authでログイン済みかどうか
// 修正後
const hasUserAuthenticated = useMemo<boolean>(() => !!currentUser && !!currentUser.id, [currentUser]); // ユーザーがFirebase Authでログイン済みかどうか
```
以下の条件をすべて満たすときのみに、閉じることができない通知モーダルを表示する機能を`<Layout>`に追加しました。
- Firebaseでログイン済み
- DBへの情報登録がまだ
- `/auth`以下のページにいない
```ts
const shouldShowModal = useMemo(() => {
if (!hasComponentMounted) return false; // Hydrationが失敗しないようにするため
return hasUserAuthenticated && !hasUserRegisteredInfo && !isCurrentlyAtAuthPage;
}, [hasUserAuthenticated, hasUserRegisteredInfo, isCurrentlyAtAuthPage, hasComponentMounted]);
```
=> `<Layout>`にFirebaseで認証済みでなおかつ登録が済んでいないときにのみ表示されるモーダルを追加した。他修正

src/presentation/primitive/component/live-character/live-character.presenter.tsx, src/presentation/relevant/game/component/game-playground/game-playground.presenter.tsx
=> `<LiveCharacter>`をより小さくした。また、ゲーム個別ページで使われる`<GamePlayground>`内のキャラクターの大きさを、モバイルでのみ小さくした。
