- .storybook/preview.js
- close #31 
`src/styles/globals.scss`から`src/styles/global.scss`へパス指定を正しいものに変更した！！
> fix: 🐛 (.storybook/preview.js) global.scssのパス指定を正しいものに修正

- .storybook/main.js
> Storybookの設定ファイルに"@/*"で"src/*"のファイルを解決できるように`import alias`の設定を追加した。

- package.json
- src/components/Button/Button.story.tsx
- src/components/Button/index.tsx
- src/libs/twmerge/index.ts
- src/styles/storybook.scss
- yarn.lock
- close #17 
- close #33 
- Tailwindのクラス適用優先順位の問題(Issue #33)を解決するために、パッケージ`tailwind-merge`を導入した。
- 今回のボタンのホバーとクリック時のアニメーションを含む、要素消去時のアニメーションなどを扱えるアニメーションライブラリ[`framer-motion`](https://www.framer.com/motion/)を導入した。
> Buttonコンポーネントの作成、並びにTailwindのクラス適用優先順位の問題を解決するためのパッケージ`tailwind-merge`の導入

- .github/workflows/chromatic.yml
- package.json
- yarn.lock
- close #38 
Storybookのビルドが`public`ディレクトリが存在しないと失敗してしまうので、`.gitkeep`を作成した。
Chromaticの`Github Actions`の動作にはトークンを`CHROMATIC_PROJECT_TOKEN`に設定しなければならないので、誰かお願いします！！！
> Chromatic CLIの導入と、push時に動作するGithub Actionsの設定

- package.json
- src/components/Card/index.tsx
- src/components/Modal/Modal.story.tsx
- src/components/Modal/index.tsx
- yarn.lock
- close #7 
[アクセシビリティ担保のために`radix-ui`を使用しています。](https://www.radix-ui.com/docs/primitives/components/dialog)
アニメーション付きです。しかし、まだ閉じるときのアニメーションが正しく動くようにする工程が**未完了**です。
これはアニメーション用ライブラリ`framer-motion`提供の`<AnimatePresence>`の中にモーダルの展開先をしていすることで解決できます。が、**すこし手間がかかりそうなので後回しにします。**
```tsx
<Modal trigger={<Button>モーダルを開く</Button>}>
<ModalTitle>本当に良いのですか？</ModalTitle>
<ModalDescription>この動作をすると何かが起こります。画面外をクリックすると閉じることができます。</ModalDescription>
<Button>
確定<span className="text-neutral-700">押しても閉じないよ</span>
</Button>
</Modal>
```
> `<Modal>`コンポーネントと各種モーダル用コンポーネント`<ModalTitle>` `<ModalDescription>`の追加

- .storybook/main.js
- .storybook/preview.js
- package.json
- yarn.lock
> Storybookで`next/link`提供の`<Link>`を使用可能にするためにアドオン`storybook-addon-next-router`を導入した

- src/components/Navigation/index.tsx
- src/layouts/components/UserNavigationMenu/UserNavigationMenu.story.tsx
- src/layouts/components/UserNavigationMenu/index.tsx
- close #68 
リンクのルーティング先は仮のものなので要修正。
あとでちゃん説明とかきます
> `<UserNavigationMenu>`を作成した。

- .storybook/main.js
- package.json
- yarn.lock
- close #73 
どうしてもっとはやくいれておかなかったんだ
> アクセシビリティの確認のためにアドオン`@storybook/addon-a11y`を導入した。

- src/components/Link/index.tsx
- src/features/games/components/GameLinkCard/GameLinkCard.story.tsx
- src/features/games/components/GameLinkCard/index.tsx
> ゲーム一覧ページで使用するゲーム別ページへのリンクとなるコンポーネント`<GameLinkCard>`を作成した。

- package.json
- src/components/Selector/index.tsx
- src/components/Separator/Separator.story.tsx
- src/components/Separator/index.tsx
- src/components/UserInteractiveItem/UserInteractiveItem.story.tsx
- src/components/UserInteractiveItem/index.tsx
- src/components/UserItem/UserItem.story.tsx
- src/components/UserItem/index.tsx
- yarn.lock
- close #137 
- close #139 
さらに、水平・垂直区切り線を提供するコンポーネント`<Separator>`も作成した。
それにあわせて、既存の一部コードをそれを使うようにリファクタリングした！
メディアクエリ不使用のレスポンシブ対応です。したがって、2列表示した際も正しく`flex-wrap`が聞いて可読性を損なわないUIが実現できます。
そのさい、レスポンシブ関連のスタイルは使う側から隠蔽されているので全く気にせず使用できます。
```tsx
<UserInteractiveItem {...args}>
<UserItem>
<UserItemIcon iconUrl="/icons/fox.png" name="ユーザー名" />
<UserItemBio>
<UserItemName>ユーザー名</UserItemName>
<UserItemDescription>ユーザーの説明</UserItemDescription>
</UserItemBio>
<UserItemTips>ユーザーのヒント</UserItemTips>
</UserItem>
<UserInteractiveItemActionGroup>
<Button outlined>アクション1</Button>
<Button>アクション2</Button>
</UserInteractiveItemActionGroup>
</UserInteractiveItem>
```
これだけで要素の大きさに合わせて表示が変わります。
詳しくはストーリーを見てください👍
> ユーザーの情報の表示のみを担うコンポーネント群`<UserItem>`と、加えて操作可能なUIを含むことができる`<UserInteractiveItem>`を作成した。他

- src/components/Button/Button.story.tsx
- src/layouts/components/AudioControlMenu/index.tsx
- src/layouts/components/HamburgerMenu/index.tsx
- src/layouts/components/ShareButton/index.tsx
- src/layouts/components/UserNavigationMenu/index.tsx
> テキストを持たない`<Button circle>`に、読み上げ等に使われる`aria-label`を設定した。

- src/features/games/components/KickableUserInteractiveItem/KickableUserInteractiveItem.story.tsx
- src/features/games/components/KickableUserInteractiveItem/index.tsx
> ゲーム管理ページ用の参加ユーザーをキックするためUIを提供するコンポーネント<KickableUserInteractiveItem>を作成した。

- src/layouts/components/Header/index.tsx
- src/layouts/components/PageNavigationMenu/index.tsx
> Figmaの変更案の通りに`<Header>`のUIを修正した。

- src/components/Input/Input.story.tsx
- src/components/Input/index.tsx
> `<Input>`に入力値の状態に依ってバッジを付加する機能を、コンポーネント`<InputOverlay>`として分離した。

- package.json
- src/features/games/components/PointInput/PointInput.story.tsx
- src/features/games/components/PointInput/index.tsx
- src/features/games/components/PointInputUserInteractiveItem/PointInputUserInteractiveItem.story.tsx
- src/features/games/components/PointInputUserInteractiveItem/index.tsx
- yarn.lock
> ユーザーの情報とともに、ポイントを入力できる増減ボタン付の入力欄を表示できるコンポーネント`<PointInputUserInteractiveItem>`を作成した。

- src/pages/_document.tsx
> `_document.tsx`内で定義されていた不要な`favicon`用の`<link>`を削除した。

- src/layouts/components/CommonMeta/index.tsx
> Twitter用の絶対パス指定のOGP画像を追加した。

- src/presentation/relevant/game/component/game-status-indicator/game-status-indicator.presenter.tsx
- src/presentation/relevant/game/component/game-status-indicator/game-status-indicator.story.tsx
- close #182 
子要素として`<LiveCharacter>`を複数渡すことで、参加者のキャラクターを表示させます。
このとき、参加者数は渡した子要素の数から計算されます。
複数の満たされていないデザインの要件 #201  がありますが、IFはこれで確定なのでPRをだしました。
> ゲームの参加者情報を示すコンポーネント`<GameStatusIndicator>`を作成した。

- src/presentation/layout/component/user-navigation-menu/hook/use-user-navigation-menu.hook.ts
- src/use-case/user/use-current-user-id.use-case.ts
> fix: 🐞 (useCurrentUserIdUseCase) User.id | null | undefinedを返却できるように修正

- src/state/audio/audio-resource.tsx
> fix: 🐞 (AudioResource) 作曲者の情報を希望に合わせて変更した。

- src/state/audio/audio-auto-play.tsx
> fix: 🐞 (src/state/audio/audio-auto-play.tsx) 音楽の自動再生機能を無効化した。

- src/pages/auth/index.tsx
- src/presentation/layout/component/user-navigation-menu/user-navigation-menu.presenter.tsx
- src/presentation/relevant/auth/auth.page.tsx
くっそ簡易ですがそもそもデザインがないので赦して。
- close #18
> feat: ✨ サインイン・サインアップ画面を作成

- src/infra/graphql/document/mutation/join-game.gql
- src/infra/graphql/document/query/check-user-existance.gql
- src/infra/graphql/document/query/find-ranking-position.gql
- src/infra/graphql/document/query/find-user-consumable-point.gql
- src/infra/graphql/document/query/find-user-meta-data.gql
- src/infra/graphql/document/query/get-ranking.gql
- src/infra/graphql/document/subscription/updated-ranking.gql
- src/infra/graphql/generated/graphql.ts
- src/infra/graphql/schema.json
- src/presentation/relevant/new-user/new-user.page.tsx
- src/use-case/ranking/use-realtime-ranking-category-data.use-case.ts
- 一部を`id`からFirebase由来のidである`authId`へ変更した。
- enum`Date`の名前を`RankingPeriod`に変更した。
> サーバー側でのGraphQLスキーマの変更に合わせてコードを修正した。

- src/infra/graphql/document/query/check-user-existance.gql
- src/infra/graphql/generated/graphql.ts
- src/use-case/user/use-check-user-existance.use-case.ts
> fix: 🐛 (GraphQL Query CheckUserExistance) 受け取る変数の名前を`id`から`authId`に変更した。

- src/presentation/relevant/game/game.page.tsx
> `ExitGame`と`JoinGame`の呼び出される条件が逆になっている問題を修正した。

- src/presentation/relevant/new-user/component/send/send.container.tsx
- src/presentation/relevant/new-user/component/send/send.presenter.tsx
- src/presentation/relevant/new-user/new-user.page.tsx
> feat: ✨ (relevant/new-user) SendのonClick時にボタンでローディングを表現するように修正

- src/infra/graphql/document/mutation/increment-point.gql
- src/infra/graphql/generated/graphql.ts
- src/pages/games/admin/coin-dropping.tsx
- src/pages/games/admin/iceraze.tsx
- src/pages/games/admin/poker.tsx
- src/pages/games/admin/president.tsx
- src/pages/games/admin/we-didnt-playtest.tsx
- src/pages/games/admin/xeno.tsx
- src/presentation/relevant/game/component/point-input-form/point-input-form.presenter.tsx
- src/presentation/relevant/game/component/point-input-form/point-input-form.story.tsx
- src/presentation/relevant/game/component/point-input/point-input.presenter.tsx
- src/presentation/relevant/game/component/point-input/point-input.story.tsx
- src/presentation/relevant/game/component/user-kick-form/user-kick-form.presenter.tsx
- src/presentation/relevant/game/component/user-kick-form/user-kick-form.story.tsx
- src/presentation/relevant/game/game-admin.page.tsx
- src/presentation/relevant/game/game-admin.presenter.tsx
- src/presentation/relevant/game/game-admin.story.tsx
- src/presentation/relevant/game/game.page.tsx
- src/use-case/user/use-increment-point.use-case.ts
> ゲーム用管理者ページ`/games/admin/xeno`, `/games/admin/iceraze`, `... +4`を作成した。

- src/presentation/relevant/game/game.page.tsx
- close #265 
ゲームからの退出が可能になりました
> fix: 🐛 (Game) ゲームからの退出と自身の参加の有無の計算に、FirebaseのidではなくDBのidを使うよう変更した。

- src/presentation/relevant/ranking/ranking.presenter.tsx
> feat: ✨ (Ranking) ランキングで選択されている日時の初期値を現在の日付に基づいて解決するようにした。

- src/presentation/primitive/component/loading-screen/loading-screen.presenter.tsx
- src/presentation/primitive/component/loading-screen/loading-screen.story.tsx
- src/presentation/relevant/game/game-admin.presenter.tsx
> 読み込み中の画面表示用のコンポーネント`<LoadingScreen>`を作成した。

- src/pages/auth/is-new-user.tsx
- src/pages/profile.tsx
- src/pages/ranking.tsx
- src/presentation/primitive/component/button/button.presenter.tsx
- src/presentation/relevant/index/temporal-index.page.tsx
> 仮のLPの内容を改善した。また、ページのタイトルの書式を統一した。
